---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[xdebug::default]
    attributes:
      xdebug:
        stand_along: true
        execute_php5enmod: true
        config_file: '/etc/php5/mods-available/xdebug.ini'
        web_server:
          service_name: ''
